# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui
from Scripts.Utils import get_config_path, resource_path
try:
    from Scripts.LLM import LLMHandler
except ImportError:
    LLMHandler = None
import json
import functools

class Config_Ui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(570, 550)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"微软雅黑\";")
        Dialog.setWindowIcon(QtGui.QIcon(resource_path("UI\\Image\\favicon.ico")))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -56, 393, 580))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.danmu_config = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.danmu_config.setObjectName("danmu_config")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.danmu_config)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.danmu_on = QtWidgets.QCheckBox(self.danmu_config)
        self.danmu_on.setObjectName("danmu_on")
        self.verticalLayout_2.addWidget(self.danmu_on)
        self.when_danmu_on = QtWidgets.QWidget(self.danmu_config)
        self.when_danmu_on.setEnabled(False)
        self.when_danmu_on.setObjectName("when_danmu_on")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.when_danmu_on)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.when_danmu_on)
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.danmu_spinBox = QtWidgets.QSpinBox(self.when_danmu_on)
        self.danmu_spinBox.setMaximum(32767)
        self.danmu_spinBox.setProperty("value", 5)
        self.danmu_spinBox.setObjectName("danmu_spinBox")
        self.verticalLayout_3.addWidget(self.danmu_spinBox)
        self.verticalLayout_2.addWidget(self.when_danmu_on)
        self.verticalLayout_12.addWidget(self.danmu_config)
        self.audio_config = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.audio_config.setObjectName("audio_config")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.audio_config)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.audio_on = QtWidgets.QCheckBox(self.audio_config)
        self.audio_on.setObjectName("audio_on")
        self.verticalLayout_4.addWidget(self.audio_on)
        self.when_audio_on = QtWidgets.QWidget(self.audio_config)
        self.when_audio_on.setEnabled(False)
        self.when_audio_on.setObjectName("when_audio_on")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.when_audio_on)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_4 = QtWidgets.QWidget(self.when_audio_on)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_11.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.verticalLayout_10.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.when_audio_on)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.when_audio_on_1 = QtWidgets.QWidget(self.widget_3)
        self.when_audio_on_1.setObjectName("when_audio_on_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.when_audio_on_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.self_danmu = QtWidgets.QCheckBox(self.when_audio_on_1)
        self.self_danmu.setObjectName("self_danmu")
        self.verticalLayout_7.addWidget(self.self_danmu)
        self.others_danmu = QtWidgets.QCheckBox(self.when_audio_on_1)
        self.others_danmu.setObjectName("others_danmu")
        self.verticalLayout_7.addWidget(self.others_danmu)
        self.receive_problem = QtWidgets.QCheckBox(self.when_audio_on_1)
        self.receive_problem.setObjectName("receive_problem")
        self.verticalLayout_7.addWidget(self.receive_problem)
        self.answer_result = QtWidgets.QCheckBox(self.when_audio_on_1)
        self.answer_result.setObjectName("answer_result")
        self.verticalLayout_7.addWidget(self.answer_result)
        self.horizontalLayout_4.addWidget(self.when_audio_on_1)
        self.when_audio_on_2 = QtWidgets.QWidget(self.widget_3)
        self.when_audio_on_2.setObjectName("when_audio_on_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.when_audio_on_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.self_called = QtWidgets.QCheckBox(self.when_audio_on_2)
        self.self_called.setObjectName("self_called")
        self.verticalLayout_6.addWidget(self.self_called)
        self.others_called = QtWidgets.QCheckBox(self.when_audio_on_2)
        self.others_called.setObjectName("others_called")
        self.verticalLayout_6.addWidget(self.others_called)
        self.course = QtWidgets.QCheckBox(self.when_audio_on_2)
        self.course.setObjectName("course")
        self.verticalLayout_6.addWidget(self.course)
        self.network = QtWidgets.QCheckBox(self.when_audio_on_2)
        self.network.setObjectName("network")
        self.verticalLayout_6.addWidget(self.network)
        self.horizontalLayout_4.addWidget(self.when_audio_on_2)
        self.verticalLayout_10.addWidget(self.widget_3)
        self.verticalLayout_4.addWidget(self.when_audio_on)
        self.verticalLayout_12.addWidget(self.audio_config)
        self.answer_config = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.answer_config.setObjectName("answer_config")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.answer_config)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.answer_on = QtWidgets.QCheckBox(self.answer_config)
        self.answer_on.setObjectName("answer_on")
        self.verticalLayout_5.addWidget(self.answer_on)
        self.when_answer_on = QtWidgets.QWidget(self.answer_config)
        self.when_answer_on.setEnabled(False)
        self.when_answer_on.setObjectName("when_answer_on")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.when_answer_on)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.when_answer_on)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.delay_time_radio_1 = QtWidgets.QRadioButton(self.when_answer_on)
        self.delay_time_radio_1.setChecked(True)
        self.delay_time_radio_1.setObjectName("delay_time_radio_1")
        self.verticalLayout_8.addWidget(self.delay_time_radio_1)
        self.delay_time_radio_2 = QtWidgets.QRadioButton(self.when_answer_on)
        self.delay_time_radio_2.setObjectName("delay_time_radio_2")
        self.verticalLayout_8.addWidget(self.delay_time_radio_2)
        self.when_delay_time_2 = QtWidgets.QWidget(self.when_answer_on)
        self.when_delay_time_2.setEnabled(False)
        self.when_delay_time_2.setObjectName("when_delay_time_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.when_delay_time_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.delay_time_2_input = QtWidgets.QSpinBox(self.when_delay_time_2)
        self.delay_time_2_input.setObjectName("delay_time_2_input")
        self.verticalLayout_9.addWidget(self.delay_time_2_input)
        self.label_2 = QtWidgets.QLabel(self.when_delay_time_2)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.verticalLayout_8.addWidget(self.when_delay_time_2)
        self.verticalLayout_5.addWidget(self.when_answer_on)
        self.verticalLayout_12.addWidget(self.answer_config)
        
        self.llm_config_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.llm_config_group.setObjectName("llm_config_group")
        self.verticalLayout_llm = QtWidgets.QVBoxLayout(self.llm_config_group)
        self.verticalLayout_llm.setObjectName("verticalLayout_llm")
        
        self.llm_api_key_label = QtWidgets.QLabel(self.llm_config_group)
        self.llm_api_key_label.setObjectName("llm_api_key_label")
        self.verticalLayout_llm.addWidget(self.llm_api_key_label)
        self.llm_api_key = QtWidgets.QLineEdit(self.llm_config_group)
        self.llm_api_key.setObjectName("llm_api_key")
        self.llm_api_key.setEchoMode(QtWidgets.QLineEdit.Password)
        self.verticalLayout_llm.addWidget(self.llm_api_key)
        
        self.llm_base_url_label = QtWidgets.QLabel(self.llm_config_group)
        self.llm_base_url_label.setObjectName("llm_base_url_label")
        self.verticalLayout_llm.addWidget(self.llm_base_url_label)
        self.llm_base_url = QtWidgets.QLineEdit(self.llm_config_group)
        self.llm_base_url.setObjectName("llm_base_url")
        self.verticalLayout_llm.addWidget(self.llm_base_url)
        
        self.llm_thinking_model_label = QtWidgets.QLabel(self.llm_config_group)
        self.llm_thinking_model_label.setObjectName("llm_thinking_model_label")
        self.verticalLayout_llm.addWidget(self.llm_thinking_model_label)
        self.llm_thinking_model = QtWidgets.QLineEdit(self.llm_config_group)
        self.llm_thinking_model.setObjectName("llm_thinking_model")
        self.verticalLayout_llm.addWidget(self.llm_thinking_model)

        self.llm_vl_model_label = QtWidgets.QLabel(self.llm_config_group)
        self.llm_vl_model_label.setObjectName("llm_vl_model_label")
        self.verticalLayout_llm.addWidget(self.llm_vl_model_label)
        self.llm_vl_model = QtWidgets.QLineEdit(self.llm_config_group)
        self.llm_vl_model.setObjectName("llm_vl_model")
        self.verticalLayout_llm.addWidget(self.llm_vl_model)

        self.llm_answer_timeout_label = QtWidgets.QLabel(self.llm_config_group)
        self.llm_answer_timeout_label.setObjectName("llm_answer_timeout_label")
        self.verticalLayout_llm.addWidget(self.llm_answer_timeout_label)
        self.llm_answer_timeout = QtWidgets.QSpinBox(self.llm_config_group)
        self.llm_answer_timeout.setRange(10, 600)
        self.llm_answer_timeout.setValue(120)
        self.llm_answer_timeout.setObjectName("llm_answer_timeout")
        self.verticalLayout_llm.addWidget(self.llm_answer_timeout)

        self.llm_test_timeout_label = QtWidgets.QLabel(self.llm_config_group)
        self.llm_test_timeout_label.setObjectName("llm_test_timeout_label")
        self.verticalLayout_llm.addWidget(self.llm_test_timeout_label)
        self.llm_test_timeout = QtWidgets.QSpinBox(self.llm_config_group)
        self.llm_test_timeout.setRange(5, 120)
        self.llm_test_timeout.setValue(15)
        self.llm_test_timeout.setObjectName("llm_test_timeout")
        self.verticalLayout_llm.addWidget(self.llm_test_timeout)

        self.llm_save_log = QtWidgets.QCheckBox(self.llm_config_group)
        self.llm_save_log.setObjectName("llm_save_log")
        self.llm_save_log.setChecked(True)
        self.verticalLayout_llm.addWidget(self.llm_save_log)

        self.test_llm_btn = QtWidgets.QPushButton(self.llm_config_group)
        self.test_llm_btn.setObjectName("test_llm_btn")
        self.verticalLayout_llm.addWidget(self.test_llm_btn)
        
        self.verticalLayout_12.addWidget(self.llm_config_group)

        self.other_config_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.other_config_group.setObjectName("other_config_group")
        self.verticalLayout_other = QtWidgets.QVBoxLayout(self.other_config_group)
        self.verticalLayout_other.setObjectName("verticalLayout_other")
        
        self.auto_save_ppt = QtWidgets.QCheckBox(self.other_config_group)
        self.auto_save_ppt.setObjectName("auto_save_ppt")
        self.verticalLayout_other.addWidget(self.auto_save_ppt)
        
        self.enable_devtools = QtWidgets.QCheckBox(self.other_config_group)
        self.enable_devtools.setObjectName("enable_devtools")
        self.verticalLayout_other.addWidget(self.enable_devtools)
        
        self.verticalLayout_12.addWidget(self.other_config_group)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.btn_wid = QtWidgets.QWidget(Dialog)
        self.btn_wid.setObjectName("btn_wid")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.btn_wid)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save = QtWidgets.QPushButton(self.btn_wid)
        self.save.setMaximumSize(QtCore.QSize(16777215, 40))
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        self.cancel = QtWidgets.QPushButton(self.btn_wid)
        self.cancel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout.addWidget(self.btn_wid)

        # 动作绑定
        self.cancel.clicked.connect(Dialog.reject)
        self.danmu_on.stateChanged.connect(self.enable_danmu_config)
        self.audio_on.stateChanged.connect(self.enable_audio_config)
        self.answer_on.stateChanged.connect(self.enable_answer_config)
        self.delay_time_radio_1.clicked.connect(self.enable_delay_custom)
        self.delay_time_radio_2.clicked.connect(self.enable_delay_custom)
        self.save.clicked.connect(functools.partial(self.save_config,dialog=Dialog))
        self.test_llm_btn.clicked.connect(self.test_llm_connection)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def enable_danmu_config(self):
        # 启用自动弹幕详细配置Widget
        if self.danmu_on.isChecked():
            self.when_danmu_on.setEnabled(True)
        else:   
            self.when_danmu_on.setEnabled(False)

    def enable_audio_config(self):
        # 启用语言提醒详细配置Widget
        if self.audio_on.isChecked():
            self.when_audio_on.setEnabled(True)
        else:   
            self.when_audio_on.setEnabled(False)
    
    def enable_answer_config(self):
        # 启用自动答题详细配置Widget
        if self.answer_on.isChecked():
            self.when_answer_on.setEnabled(True)
            self.llm_config_group.setEnabled(True)
        else:   
            self.when_answer_on.setEnabled(False)
            self.llm_config_group.setEnabled(False)

    def enable_delay_custom(self):
        # 启用自定义延迟详细配置Widget
        if self.delay_time_radio_2.isChecked():
            self.when_delay_time_2.setEnabled(True)
        else:
            self.when_delay_time_2.setEnabled(False)

    def load_config(self, config):
        # 弹幕配置
        self.danmu_on.setChecked(config["auto_danmu"])
        self.danmu_spinBox.setValue(config["danmu_config"]["danmu_limit"])
        # 语音配置
        self.audio_on.setChecked(config["audio_on"])
        self.self_danmu.setChecked(config["audio_config"]["audio_type"]["send_danmu"])
        self.others_danmu.setChecked(config["audio_config"]["audio_type"]["others_danmu"])
        self.receive_problem.setChecked(config["audio_config"]["audio_type"]["receive_problem"])
        self.answer_result.setChecked(config["audio_config"]["audio_type"]["answer_result"])
        self.self_called.setChecked(config["audio_config"]["audio_type"]["im_called"])
        self.others_called.setChecked(config["audio_config"]["audio_type"]["others_called"])
        self.course.setChecked(config["audio_config"]["audio_type"]["course_info"])
        self.network.setChecked(config["audio_config"]["audio_type"]["network_info"])
        # 答题配置
        self.answer_on.setChecked(config["auto_answer"])
        if config["answer_config"]["answer_delay"]["type"] == 1:
            self.delay_time_radio_1.setChecked(True)
        elif config["answer_config"]["answer_delay"]["type"] == 2:
            self.delay_time_radio_2.setChecked(True)
        self.delay_time_2_input.setValue(config["answer_config"]["answer_delay"]["custom"]["time"])
        
        # LLM配置
        llm_cfg = config.get("llm_config", {})
        self.llm_api_key.setText(llm_cfg.get("api_key", ""))
        self.llm_base_url.setText(llm_cfg.get("base_url", "https://api.openai.com"))
        default_model = llm_cfg.get("model", "gpt-4o-mini")
        thinking_model = llm_cfg.get("thinking_model", default_model)
        vl_model = llm_cfg.get("vl_model", thinking_model)
        self.llm_thinking_model.setText(thinking_model)
        self.llm_vl_model.setText(vl_model)
        self.llm_answer_timeout.setValue(int(llm_cfg.get("answer_timeout", 120)))
        self.llm_test_timeout.setValue(int(llm_cfg.get("test_timeout", 15)))
        self.llm_save_log.setChecked(bool(llm_cfg.get("save_log", True)))
        
        self.auto_save_ppt.setChecked(config.get("auto_save_ppt", False))
        self.enable_devtools.setChecked(config.get("enable_devtools", False))
        
        self.dialog_config = config

    def save_config(self, dialog):
        config = self.dialog_config
        # 弹幕配置
        config["auto_danmu"] = self.danmu_on.isChecked()
        config["danmu_config"]["danmu_limit"] = self.danmu_spinBox.value()
        # 语音配置
        config["audio_on"] = self.audio_on.isChecked()
        config["audio_config"]["audio_type"]["send_danmu"] = self.self_danmu.isChecked()
        config["audio_config"]["audio_type"]["others_danmu"] = self.others_danmu.isChecked()
        config["audio_config"]["audio_type"]["receive_problem"] = self.receive_problem.isChecked()
        config["audio_config"]["audio_type"]["answer_result"] = self.answer_result.isChecked()
        config["audio_config"]["audio_type"]["im_called"] = self.self_called.isChecked()
        config["audio_config"]["audio_type"]["others_called"] = self.others_called.isChecked()
        config["audio_config"]["audio_type"]["course_info"] = self.course.isChecked()
        config["audio_config"]["audio_type"]["network_info"] = self.network.isChecked()
        # 答题配置
        config["auto_answer"] = self.answer_on.isChecked()
        if self.delay_time_radio_1.isChecked():
            config["answer_config"]["answer_delay"]["type"] = 1
        elif self.delay_time_radio_2.isChecked():
            config["answer_config"]["answer_delay"]["type"] = 2
        config["answer_config"]["answer_delay"]["custom"]["time"] = self.delay_time_2_input.value()
        
        # LLM配置
        if "llm_config" not in config:
            config["llm_config"] = {}
        thinking_model = self.llm_thinking_model.text().strip()
        vl_model = self.llm_vl_model.text().strip()
        if not thinking_model:
            thinking_model = "gpt-4o-mini"
        if not vl_model:
            vl_model = thinking_model
        config["llm_config"]["api_key"] = self.llm_api_key.text()
        config["llm_config"]["base_url"] = self.llm_base_url.text()
        config["llm_config"]["model"] = thinking_model
        config["llm_config"]["thinking_model"] = thinking_model
        config["llm_config"]["vl_model"] = vl_model
        config["llm_config"]["answer_timeout"] = self.llm_answer_timeout.value()
        config["llm_config"]["test_timeout"] = self.llm_test_timeout.value()
        config["llm_config"]["save_log"] = self.llm_save_log.isChecked()
        
        config["auto_save_ppt"] = self.auto_save_ppt.isChecked()
        config["enable_devtools"] = self.enable_devtools.isChecked()
        
        # 保存
        config_path = get_config_path()
        with open(config_path,"w+") as f:
            json.dump(config,f)
        dialog.accept()
    
    def test_llm_connection(self):
        if not LLMHandler:
            QtWidgets.QMessageBox.warning(None, "错误", "LLM 模块加载失败，请检查环境。")
            return
            
        api_key = self.llm_api_key.text().strip()
        base_url = self.llm_base_url.text().strip()
        thinking_model = self.llm_thinking_model.text().strip()
        vl_model = self.llm_vl_model.text().strip()
        answer_timeout = self.llm_answer_timeout.value()
        test_timeout = self.llm_test_timeout.value()
        
        if not api_key:
            QtWidgets.QMessageBox.warning(None, "提示", "请输入 API Key")
            return

        if not thinking_model:
            QtWidgets.QMessageBox.warning(None, "提示", "请输入 Thinking 模型")
            return
        if not vl_model:
            vl_model = thinking_model
            
        try:
            handler = LLMHandler(
                api_key=api_key,
                base_url=base_url,
                thinking_model=thinking_model,
                vl_model=vl_model,
                answer_timeout=answer_timeout,
                test_timeout=test_timeout,
                save_log=False,
            )
            think_ok, think_msg = handler.test_connection(model=thinking_model)
            if vl_model == thinking_model:
                vl_ok, vl_msg = think_ok, "与 Thinking 模型相同，复用同一连接测试结果"
            else:
                vl_ok, vl_msg = handler.test_connection(model=vl_model)

            if think_ok and vl_ok:
                QtWidgets.QMessageBox.information(None, "测试成功", f"Thinking模型: {think_msg}\nVL模型: {vl_msg}")
            else:
                QtWidgets.QMessageBox.warning(None, "测试失败", f"Thinking模型: {think_msg}\nVL模型: {vl_msg}")
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "错误", f"发生异常: {str(e)}")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "配置"))
        self.danmu_config.setTitle(_translate("Dialog", "弹幕配置"))
        self.danmu_on.setText(_translate("Dialog", "启用自动发送弹幕"))
        self.label.setText(_translate("Dialog", "自动弹幕阈值（每分钟内收到n条弹幕后自动发送相同弹幕）"))
        self.audio_config.setTitle(_translate("Dialog", "语音配置"))
        self.audio_on.setText(_translate("Dialog", "启用语音提醒"))
        self.label_4.setText(_translate("Dialog", "需要语音提醒的内容"))
        self.self_danmu.setText(_translate("Dialog", "自动发送弹幕情况提醒"))
        self.others_danmu.setText(_translate("Dialog", "他人弹幕发送语音提醒"))
        self.receive_problem.setText(_translate("Dialog", "收到题目提醒"))
        self.answer_result.setText(_translate("Dialog", "自动答题情况提醒"))
        self.self_called.setText(_translate("Dialog", "自己被点名提醒"))
        self.others_called.setText(_translate("Dialog", "他人被点名提醒"))
        self.course.setText(_translate("Dialog", "课程相关提醒"))
        self.network.setText(_translate("Dialog", "网络断开/重连提醒"))
        self.answer_config.setTitle(_translate("Dialog", "答题配置"))
        self.answer_on.setText(_translate("Dialog", "启用自动答题"))
        self.label_3.setText(_translate("Dialog", "答题延迟时长"))
        self.delay_time_radio_1.setText(_translate("Dialog", "系统默认（随机决定时间）"))
        self.delay_time_radio_2.setText(_translate("Dialog", "自定义（于收到题目n秒后自动回答）"))
        self.label_2.setText(_translate("Dialog", "注：如果您采用自定义延迟时长，当延迟时长大于题目所给时限时，将按照系统默认算法重新计算延迟时长。"))
        self.llm_config_group.setTitle(_translate("Dialog", "LLM 配置"))
        self.llm_api_key_label.setText(_translate("Dialog", "API Key (如 sk-...)"))
        self.llm_base_url_label.setText(_translate("Dialog", "Base URL (如 https://api.siliconflow.cn/v1)"))
        self.llm_thinking_model_label.setText(_translate("Dialog", "Thinking Model (默认主解题模型)"))
        self.llm_vl_model_label.setText(_translate("Dialog", "VL Model (图像题回退模型)"))
        self.llm_answer_timeout_label.setText(_translate("Dialog", "答题请求超时（秒，建议深度模型 >=120）"))
        self.llm_test_timeout_label.setText(_translate("Dialog", "连接测试读取超时（秒）"))
        self.llm_save_log.setText(_translate("Dialog", "保存 LLM 调用日志（logs/llm_*.jsonl）"))
        self.test_llm_btn.setText(_translate("Dialog", "测试 LLM 连接"))
        
        self.other_config_group.setTitle(_translate("Dialog", "其他配置"))
        self.auto_save_ppt.setText(_translate("Dialog", "自动保存 PPT (保存至课程文件夹)"))
        self.enable_devtools.setText(_translate("Dialog", "启用 DevTools 记录器 (保存在 logs 文件夹)"))

        self.save.setText(_translate("Dialog", "保存"))
        self.cancel.setText(_translate("Dialog", "取消"))
