# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from UI.Login import Login_Ui
from UI.Config import Config_Ui
from Scripts.Utils import *
from Scripts.Monitor import monitor
import os
import json
import datetime
import threading
    
class MainWindow_Ui(QtCore.QObject):
    # 需要建立信号槽，解决无法在线程中修改UI值问题
    add_message_signal = QtCore.pyqtSignal(str,int)
    add_course_signal = QtCore.pyqtSignal(list,int)
    del_course_signal = QtCore.pyqtSignal(int)
    update_ppt_image_signal = QtCore.pyqtSignal(str, str)

    def setupUi(self, MainWindow):
        # 对象变量初始化
        self.table_index = []
        self.is_active = False
        self.skip_auto_login_until_start = False
        self.schedule_start_time = None
        self.schedule_end_time = None
        self.schedule_start_triggered = False
        self.schedule_timer = QtCore.QTimer()
        self.schedule_timer.setInterval(1000)
        self.schedule_timer.timeout.connect(self.check_schedule_task)

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setWindowIcon(QtGui.QIcon(resource_path("UI\\Image\\favicon.ico")))
        self.Window = QtWidgets.QWidget(MainWindow)
        self.Window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Window.setObjectName("Window")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Window)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Menu = QtWidgets.QWidget(self.Window)
        self.Menu.setStyleSheet("background-color: rgb(17, 17, 17);")
        self.Menu.setObjectName("Menu")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Menu)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.Menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(32, 32))
        self.label.setStyleSheet("border-radius:10px;\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(resource_path("UI\\Image\\NoRainClassroom.jpg")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.Menu)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"黑体\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.server_select = QtWidgets.QComboBox(self.Menu)
        self.server_select.setMaximumSize(QtCore.QSize(170, 400))
        self.server_select.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.server_select.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.server_select.setObjectName("server_select")
        self.horizontalLayout_3.addWidget(self.server_select)
        self.active_btn = QtWidgets.QPushButton(self.Menu)
        self.active_btn.setMaximumSize(QtCore.QSize(100, 400))
        self.active_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.active_btn.setAutoFillBackground(False)
        self.active_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.active_btn.setObjectName("active_btn")
        self.horizontalLayout_3.addWidget(self.active_btn)
        self.login_btn = QtWidgets.QPushButton(self.Menu)
        self.login_btn.setMaximumSize(QtCore.QSize(100, 400))
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_btn.setAutoFillBackground(False)
        self.login_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout_3.addWidget(self.login_btn)
        self.config_btn = QtWidgets.QPushButton(self.Menu)
        self.config_btn.setMaximumSize(QtCore.QSize(100, 400))
        self.config_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.config_btn.setAutoFillBackground(False)
        self.config_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.config_btn.setObjectName("config_btn")
        self.horizontalLayout_3.addWidget(self.config_btn)
        self.schedule_btn = QtWidgets.QPushButton(self.Menu)
        self.schedule_btn.setMaximumSize(QtCore.QSize(120, 400))
        self.schedule_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.schedule_btn.setAutoFillBackground(False)
        self.schedule_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.schedule_btn.setObjectName("schedule_btn")
        self.horizontalLayout_3.addWidget(self.schedule_btn)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(4, 1)
        self.horizontalLayout_3.setStretch(5, 1)
        self.horizontalLayout_3.setStretch(6, 1)
        self.horizontalLayout_3.setStretch(7, 1)
        self.verticalLayout.addWidget(self.Menu)
        self.Table = QtWidgets.QGroupBox(self.Window)
        self.Table.setStyleSheet("color: rgb(209, 209, 209);\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(0, 0, 0);")
        self.Table.setObjectName("Table")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Table)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.Table)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.Table)
        self.PPTPreview = QtWidgets.QGroupBox(self.Window)
        self.PPTPreview.setStyleSheet("color: rgb(209, 209, 209);\n"
    "font: 10pt \"微软雅黑\";\n"
    "color: rgb(0, 0, 0);")
        self.PPTPreview.setObjectName("PPTPreview")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.PPTPreview)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ppt_info_label = QtWidgets.QLabel(self.PPTPreview)
        self.ppt_info_label.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.ppt_info_label.setText("当前PPT：暂无")
        self.ppt_info_label.setObjectName("ppt_info_label")
        self.verticalLayout_4.addWidget(self.ppt_info_label)
        self.ppt_image_label = QtWidgets.QLabel(self.PPTPreview)
        self.ppt_image_label.setMinimumSize(QtCore.QSize(0, 180))
        self.ppt_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ppt_image_label.setStyleSheet("background-color: rgb(40, 40, 40); color: rgb(220, 220, 220);")
        self.ppt_image_label.setText("暂无PPT图片")
        self.ppt_image_label.setObjectName("ppt_image_label")
        self.verticalLayout_4.addWidget(self.ppt_image_label)
        self.verticalLayout.addWidget(self.PPTPreview)
        self.Output = QtWidgets.QGroupBox(self.Window)
        self.Output.setStyleSheet("color: rgb(209, 209, 209);\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(0, 0, 0);")
        self.Output.setObjectName("Output")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Output)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.output_textarea = QtWidgets.QTextBrowser(self.Output)
        self.output_textarea.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"微软雅黑\";")
        self.output_textarea.setObjectName("output_textarea")
        self.verticalLayout_2.addWidget(self.output_textarea)
        self.verticalLayout.addWidget(self.Output)
        MainWindow.setCentralWidget(self.Window)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 按钮事件绑定
        self.config_btn.clicked.connect(self.show_config)
        self.login_btn.clicked.connect(self.show_login)
        self.active_btn.clicked.connect(self.active_clicked)
        self.schedule_btn.clicked.connect(self.show_schedule_dialog)
        self.server_select.currentIndexChanged.connect(self.on_server_changed)

        # 绑定信号槽
        self.add_message_signal.connect(self.add_message)
        self.add_course_signal.connect(self.add_course)
        self.del_course_signal.connect(self.del_course)
        self.update_ppt_image_signal.connect(self.update_ppt_preview)

        # 配置文件检查
        dir_route = get_config_dir()
        config_route = get_config_path()
        self.config = self.check_config(dir_route, config_route)
        self.init_server_select()

        self.add_message_signal.emit("当前版本：v0.0.4",0)
        self.add_message_signal.emit("初始化完成",0)

        # 登录状态检查
        status, user_info = self.check_login()
        if status:
            self.login_btn.setText("重新登录")
            self.add_message_signal.emit("登录成功，当前登录用户："+user_info["name"],0)
        else:
            self.login_btn.setText("登录")
            self.add_message_signal.emit("当前未登录，点击“登录”或“启用”后可进行登录",0)

        self.update_schedule_button_text()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "摸鱼课堂"))
        self.label_2.setText(_translate("MainWindow", "摸鱼课堂"))
        self.server_select.setToolTip(_translate("MainWindow", "选择雨课堂服务器"))
        self.active_btn.setText(_translate("MainWindow", "启用"))
        self.login_btn.setText(_translate("MainWindow", "登录"))
        self.config_btn.setText(_translate("MainWindow", "配置"))
        self.schedule_btn.setText(_translate("MainWindow", "定时任务"))
        self.Table.setTitle(_translate("MainWindow", "监听列表"))
        self.Output.setTitle(_translate("MainWindow", "信息"))
        self.PPTPreview.setTitle(_translate("MainWindow", "当前PPT"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "课程名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "课程标题"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "教师"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "上课时间"))
        self.Output.setTitle(_translate("MainWindow", "信息"))

    def add_course(self, row, row_count):
        # 添加课程
        # 注意：在非UI运行线程中调用该方法请对add_course_signal发送信号
        self.tableWidget.insertRow(row_count)
        # 装填当前行各列数据
        for i in range(len(row)):
            content = QtWidgets.QTableWidgetItem(str(row[i]))
            self.tableWidget.setItem(row_count,i,content)

        # 存储各行PersistentModelIndex，便于后续删除操作
        model_index = self.tableWidget.indexFromItem(content)
        per_model_index = QtCore.QPersistentModelIndex(model_index)
        self.table_index.append((row_count,per_model_index))

    def del_course(self, index):
        # 删除课程
        # 注意：在非UI运行线程中调用该方法请对del_course_signal发送信号
        for row_count,per_model_index in self.table_index:
            # 搜索传入index所对应的QPersistentModelIndex，并进行删除
            # QPersistentModelIndex对象的索引在删除过程中不会被已删除元素影响
            if row_count == index:
                self.tableWidget.removeRow(per_model_index.row())
                self.table_index.remove((row_count,per_model_index))

    def show_config(self):
        # 展示配置对话框
        dialog = QtWidgets.QDialog()
        config_ui = Config_Ui()
        config_ui.setupUi(dialog)
        # 加载配置文件
        config_ui.load_config(self.config)
        # 这里需要刷新一次自定义延迟部分的Widget
        config_ui.enable_delay_custom()
        if dialog.exec_():
            config_route = get_config_path()
            with open(config_route,"r") as f:
                self.config = json.load(f)

    def show_login(self, _bool=False, rtn_message="", auto_popup=False):
        # 展示登录对话框
        # rtn_message用于展示上次扫码登录失败的信息
        dialog = QtWidgets.QDialog()
        login_ui = Login_Ui()
        # 先加载配置，setupUi 内会启动登录 websocket 并依赖 self.config
        login_ui.load_config(self.config)
        login_ui.setupUi(dialog)

        # 将最下方登录返回值栏设置rtn_message
        login_ui.login_return.setText(rtn_message)

        # 登录成功返回1，其他情况返回0
        success = dialog.exec_()
        if success:
            config_route = get_config_path()
            with open(config_route,"r") as f:
                self.config =  json.load(f)
        # 删除涉及登录的线程
        login_ui.close_all()
        # 再次检测登录状态
        status, user_info = self.check_login()
        if status and success:
            self.add_message_signal.emit("登录成功，当前登录用户："+user_info["name"],0)
            self.login_btn.setText("重新登录")
            self.skip_auto_login_until_start = False
            return True

        if not success:
            if auto_popup:
                self.skip_auto_login_until_start = True
                self.add_message_signal.emit("已取消自动登录提示，将在点击“启用”时再次提示登录",0)
            return False

        self.add_message_signal.emit("登录失败，请点击“登录”重试",0)
        return False
        
    def check_config(self, dir_route, config_route):
        # 检查配置文件
        # 检查目录是否存在
        if not os.path.exists(dir_route):
            os.makedirs(dir_route)
        # 检查配置文件存在性及可用性
        if not os.path.exists(config_route):
            initial_data = get_initial_data()
            f = open(config_route,"w+")
            json.dump(initial_data,f)
            f.close()
            self.add_message_signal.emit("没有检测到配置文件，已自动创建",0)
            return initial_data
        else:
            try:
                with open(config_route,"r") as f:
                    data = json.load(f)
                if not isinstance(data, dict):
                    raise ValueError("Invalid config format")
                if "server" not in data:
                    data["server"] = DEFAULT_SERVER_KEY
                    with open(config_route,"w+") as f:
                        json.dump(data, f)
                self.add_message_signal.emit("配置文件已读取",0)
                return data
            except:
                with open(config_route,"w+") as f:
                    initial_data = get_initial_data()
                    json.dump(initial_data,f)
                    self.add_message_signal.emit("配置文件读取失败，已重新生成",0)
                    return initial_data

    def init_server_select(self):
        self.server_select.blockSignals(True)
        self.server_select.clear()
        for key, item in YUKETANG_SERVERS.items():
            self.server_select.addItem(item["name"], key)

        current_key = get_server_key(self.config)
        index = self.server_select.findData(current_key)
        if index < 0:
            index = self.server_select.findData(DEFAULT_SERVER_KEY)
        if index >= 0:
            self.server_select.setCurrentIndex(index)
        self.server_select.blockSignals(False)

    def on_server_changed(self):
        index = self.server_select.currentIndex()
        if index < 0:
            return
        new_key = self.server_select.itemData(index)
        new_key = get_server_key(new_key)
        old_key = get_server_key(self.config)
        if new_key == old_key:
            return

        self.config["server"] = new_key
        # 切换服务器后旧 sessionid 通常失效，清空以避免误用
        self.config["sessionid"] = ""
        config_route = get_config_path()
        with open(config_route, "w+") as f:
            json.dump(self.config, f)
        self.add_message_signal.emit(f"已切换服务器：{YUKETANG_SERVERS[new_key]['name']}", 0)
        self.add_message_signal.emit("服务器已切换，正在打开登录窗口", 0)

        if self.is_active:
            self.add_message_signal.emit("当前正在监听，请先停止监听后再登录", 0)
            return

        self.skip_auto_login_until_start = False
        self.show_login(rtn_message="服务器已切换，请重新登录", auto_popup=True)

    def check_login(self):
        # 检查登录状态
        sessionid = self.config.get("sessionid", "") if isinstance(self.config, dict) else ""
        if not sessionid:
            return False, {}

        try:
            code, user_info = get_user_info(sessionid, self.config)
            if code == 0:
                return True,user_info
            return False,user_info
        except Exception:
            return False, {}
            
    def add_message(self, message, type=0):
        # 新增输出信息，并尝试语音播报
        time = datetime.datetime.now().strftime("[%Y-%m-%d %H:%M:%S] ")
        self.output_textarea.append(time + message)
        if not type == 0:
            self.audio(message,type)

    def update_ppt_preview(self, image_path, info_text):
        self.ppt_info_label.setText(info_text if info_text else "当前PPT：暂无")

        if image_path and os.path.exists(image_path):
            pixmap = QtGui.QPixmap(image_path)
            if not pixmap.isNull():
                scaled = pixmap.scaled(self.ppt_image_label.size(), QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation)
                self.ppt_image_label.setPixmap(scaled)
                self.ppt_image_label.setText("")
                return

        self.ppt_image_label.setPixmap(QtGui.QPixmap())
        self.ppt_image_label.setText("暂无PPT图片")

    def format_schedule_time(self, dt):
        return dt.strftime("%Y-%m-%d %H:%M:%S")

    def update_schedule_button_text(self):
        if self.schedule_start_time and self.schedule_end_time:
            self.schedule_btn.setText("定时任务(已设置)")
        else:
            self.schedule_btn.setText("定时任务")

    def set_schedule_task(self, start_time, end_time):
        self.schedule_start_time = start_time
        self.schedule_end_time = end_time
        self.schedule_start_triggered = False
        self.schedule_timer.start()
        self.update_schedule_button_text()
        self.add_message_signal.emit(
            "已设置定时任务：%s 开始，%s 结束"
            % (self.format_schedule_time(start_time), self.format_schedule_time(end_time)),
            0
        )

    def clear_schedule_task(self, show_message=False):
        had_task = self.schedule_start_time is not None and self.schedule_end_time is not None
        self.schedule_start_time = None
        self.schedule_end_time = None
        self.schedule_start_triggered = False
        self.schedule_timer.stop()
        self.update_schedule_button_text()
        if had_task and show_message:
            self.add_message_signal.emit("已清除定时任务", 0)

    def show_schedule_dialog(self):
        dialog = QtWidgets.QDialog()
        dialog.setWindowTitle("定时任务")
        dialog.setWindowIcon(QtGui.QIcon(resource_path("UI\\Image\\favicon.ico")))
        dialog.resize(420, 220)
        dialog.setStyleSheet("background-color: rgb(255, 255, 255); font: 9pt \"微软雅黑\";")

        layout = QtWidgets.QVBoxLayout(dialog)

        current_label = QtWidgets.QLabel(dialog)
        current_label.setWordWrap(True)
        if self.schedule_start_time and self.schedule_end_time:
            current_label.setText(
                "当前任务：%s 开始，%s 结束"
                % (self.format_schedule_time(self.schedule_start_time), self.format_schedule_time(self.schedule_end_time))
            )
        else:
            current_label.setText("当前任务：未设置")
        layout.addWidget(current_label)

        form_layout = QtWidgets.QFormLayout()
        start_edit = QtWidgets.QDateTimeEdit(dialog)
        end_edit = QtWidgets.QDateTimeEdit(dialog)
        for edit in (start_edit, end_edit):
            edit.setCalendarPopup(True)
            edit.setDisplayFormat("yyyy-MM-dd HH:mm:ss")

        now_qt = QtCore.QDateTime.currentDateTime()
        default_start = now_qt.addSecs(60)
        default_end = now_qt.addSecs(3600)
        if self.schedule_start_time and self.schedule_end_time:
            default_start = QtCore.QDateTime.fromSecsSinceEpoch(int(self.schedule_start_time.timestamp()))
            default_end = QtCore.QDateTime.fromSecsSinceEpoch(int(self.schedule_end_time.timestamp()))

        start_edit.setDateTime(default_start)
        end_edit.setDateTime(default_end)

        def sync_end_minimum():
            end_edit.setMinimumDateTime(start_edit.dateTime().addSecs(1))

        sync_end_minimum()
        start_edit.dateTimeChanged.connect(lambda _dt: sync_end_minimum())

        form_layout.addRow("开始时间", start_edit)
        form_layout.addRow("结束时间", end_edit)
        layout.addLayout(form_layout)

        tip_label = QtWidgets.QLabel("说明：到达开始时间自动启动监听，到达结束时间自动停止监听。")
        tip_label.setWordWrap(True)
        layout.addWidget(tip_label)

        button_box = QtWidgets.QDialogButtonBox(
            QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Cancel,
            parent=dialog
        )
        clear_btn = button_box.addButton("清除任务", QtWidgets.QDialogButtonBox.ResetRole)
        button_box.accepted.connect(dialog.accept)
        button_box.rejected.connect(dialog.reject)
        clear_btn.clicked.connect(lambda: dialog.done(2))
        layout.addWidget(button_box)

        result = dialog.exec_()
        if result == 2:
            self.clear_schedule_task(show_message=True)
            return
        if result != QtWidgets.QDialog.Accepted:
            return

        start_time = start_edit.dateTime().toPyDateTime()
        end_time = end_edit.dateTime().toPyDateTime()
        now = datetime.datetime.now()

        if start_time <= now:
            QtWidgets.QMessageBox.warning(None, "提示", "开始时间必须晚于当前时间")
            return
        if end_time <= start_time:
            QtWidgets.QMessageBox.warning(None, "提示", "结束时间必须晚于开始时间")
            return

        self.set_schedule_task(start_time, end_time)

    def check_schedule_task(self):
        if not self.schedule_start_time or not self.schedule_end_time:
            return

        now = datetime.datetime.now()

        if not self.schedule_start_triggered and now >= self.schedule_start_time:
            self.schedule_start_triggered = True
            if self.is_active:
                self.add_message_signal.emit("定时任务开始时间已到，当前已在监听中", 0)
            else:
                status, _ = self.check_login()
                if not status:
                    rtn = self.show_login(rtn_message="定时任务开始前请先登录")
                    if not rtn:
                        self.add_message_signal.emit("定时任务启动失败：登录取消或失败，已取消本次定时任务", 0)
                        self.clear_schedule_task()
                        return
                self.active()
                self.add_message_signal.emit("定时任务开始时间已到，已自动开始监听", 0)

        if now >= self.schedule_end_time:
            if self.is_active:
                self.deactive()
                self.add_message_signal.emit("定时任务结束时间已到，已自动停止监听", 0)
            else:
                self.add_message_signal.emit("定时任务结束时间已到，本次定时任务已结束", 0)
            self.clear_schedule_task()

    def active_clicked(self):
        # 启动按钮被点击
        if self.is_active:
            self.deactive()
        else:
            status, _ = self.check_login()
            if not status:
                rtn = self.show_login(rtn_message="启动监听前请先登录")
                if not rtn:
                    return
            self.active()

    def active(self):
        # 启动
        if self.is_active:
            return
        self.monitor_t = threading.Thread(target=monitor,args=(self,),daemon=True)
        self.monitor_t.start()
        self.is_active = True
        self.active_btn.setText("停止监听")
        self.add_message_signal.emit("启动成功",0)
    
    def deactive(self):
        # 停止
        self.active_btn.setText("停止中...")
        self.active_btn.setEnabled(False)
        # 强制刷新UI
        QtWidgets.qApp.processEvents()
        self.is_active = False
        self.monitor_t.join()
        self.active_btn.setEnabled(True)
        self.active_btn.setText("启动")
        self.add_message_signal.emit("停止成功",0)

    def audio(self, message, type):
        '''
        type
        0: 默认，未分类音频
        1: 自动发送弹幕成功
        2: 他人弹幕发送
        3: 收到题目
        4: 自动答题情况
        5: 自己被点名
        6: 他人被点名
        7: 课程相关
        8: 网络断开/重连
        '''
        # 尝试播放语音提示
        audio_on = self.config["audio_on"]
        if audio_on:
            audio_type = self.config["audio_config"]["audio_type"]
            if \
            (type == 1 and audio_type["send_danmu"]) or \
            (type == 2 and audio_type["others_danmu"]) or \
            (type == 3 and audio_type["receive_problem"]) or \
            (type == 4 and audio_type["answer_result"]) or \
            (type == 5 and audio_type["im_called"]) or \
            (type == 6 and audio_type["others_called"]) or \
            (type == 7 and audio_type["course_info"]) or \
            (type == 8 and audio_type["network_info"]) :
                threading.Thread(target=say_something,args=(message,),daemon=True).start()